- hosts: dps_seafile
  tasks:
    - name: Get git rev version
      local_action: command git rev-parse --short HEAD
      register: GIT_COMMIT_ID
    - name: Build
      vars:
        - BUILD_TIME: "{{ansible_date_time.iso8601}}"
        - GIT_TAG: "{{GIT_COMMIT_ID.stdout}}"
        - LDFLAGS: -ldflags "-X main.GitTag={{GIT_TAG}} -X main.BuildTime={{BUILD_TIME}}"
      environment:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64
      local_action: command go build -o dist/ -i {{LDFLAGS}}
        # 下一步，上传wfRadius文件去sae
