# - hosts: dps_seafile
- hosts: localhost
  tasks:
    - name: Get git rev version
      local_action: command git rev-parse --short HEAD
      register: GIT_COMMIT_ID
    - name: Build
      vars:
        - BUILD_TIME: "{{ansible_date_time.iso8601}}"
        - GIT_TAG: GIT_COMMIT_ID.stdout
        - LDFLAGS: -ldflags "-X main.GitTag={{GIT_TAG}} -X main.BuildTime={{BUILD_TIME}}"
      environment:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
      local_action: command go build -o dist/ -i {{LDFLAGS}}
    # - name: Update database schema
      # local_action: command sql-migrate up --env=production
    - name: Push local folder to remote host
      synchronize:
        src: dist/
        dest: /home/wgjtyu/wfradio/
        rsync_opts: '-avcz'
    - name: Run new wfbackend
      command: sh start.sh
      # command: chdir=/www/wfbackend sh start.sh
      args:
        chdir: /home/wgjtyu/wfradio/