// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wfRadius/src/handler"
	"wfRadius/src/root"
	"wfRadius/src/root/startup"
	"wfRadius/src/wifilog"
	"wfRadius/src/ws"
)

// Injectors from wire.go:

func BuildApp() (*root.App, error) {
	mConfig := startup.InitCfg()
	logger := startup.NewZap(mConfig)
	db, err := startup.InitGorm(logger)
	if err != nil {
		return nil, err
	}
	cmdProcessor := ws.NewCmdProcessor(mConfig, logger)
	worker := ws.NewWorker(mConfig, logger, db, cmdProcessor)
	radiusServer := handler.NewRadiusServer(db, logger)
	uploader := wifilog.NewUploader(db, logger)
	app := &root.App{
		Config:   mConfig,
		DB:       db,
		Logger:   logger,
		Worker:   worker,
		RServer:  radiusServer,
		Uploader: uploader,
	}
	return app, nil
}
